# CANARY Project Configuration
# This file defines project-specific settings for requirement tracking

# Project identification
project:
  name: "."
  description: ". project with CANARY requirement tracking"
  key: "PGS"

# Requirement ID pattern for this project
# This filters which CANARY tokens are considered "real" vs examples/tests
requirements:
  # Regex pattern for valid requirement IDs in this project
  # Examples:
  #   - "PGS-[1-9][0-9]{2,}" matches PGS-100 and above
  #   - "PGS-.*" matches any PGS- prefix
  #   - "PGS-(10[0-9]|1[1-5][0-9])" matches PGS-100 through PGS-159
  id_pattern: "PGS-[1-9][0-9]{2,}"  # PGS-100 and above (excludes example IDs 001-099)

  # Alternative: explicit ranges
  # id_ranges:
  #   - "PGS-100:PGS-999"  # Inclusive range

  # Alternative: exclude patterns (for examples/tests)
  # exclude_patterns:
  #   - "PGS-0[0-9]{2}"  # Exclude PGS-001 through PGS-099 (examples)

# Scanner behavior
scanner:
  # Paths to exclude from scanning (in addition to default skip patterns)
  exclude_paths:
    - "testdata/"
    - "fixtures/"
    - "examples/"

  # File patterns to include (defaults to *.go, *.py, *.md, etc.)
  # include_patterns:
  #   - "*.go"
  #   - "*.md"
  #   - "*.py"

# Verification settings
verification:
  # Require TEST= field for TESTED status
  require_test_field: true

  # Require BENCH= field for BENCHED status
  require_bench_field: true

  # Staleness threshold in days (for --strict mode)
  staleness_days: 30
